SET TRACE_LEVEL_SYSTEM_OUT 3;
SET IGNORECASE TRUE;
SET MODE MYSQL;
CREATE SCHEMA IF NOT EXISTS SCHEMA1;
CREATE SCHEMA IF NOT EXISTS SCHEMA2;

CREATE TABLE IF NOT EXISTS schema1.sample (ID BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS schema2.sample (ID BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255), PRIMARY KEY (ID));

